version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_strong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - sql_data:/var/opt/mssql

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - minio_data:/data

  bootstrap:
    image: python:3.11-slim
    depends_on:
      sqlserver:
        condition: service_healthy
      minio:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./scripts:/app/scripts:ro
    environment:
      SQL_HOST: sqlserver
      SQL_PORT: "1433"
      SQL_USER: sa
      SQL_PASS: Your_strong@Passw0rd
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    entrypoint: ["bash", "-lc"]
    command: |
      pip install pymssql boto3 && \
      python /app/scripts/bootstrap_local.py

volumes:
  sql_data:
  minio_data: